name: Java-Wokflow

on:
  push:
    branches:
      - main
jobs:
  build:
    name: spring-pet
    runs-on: self-hosted
  steps:
    name: git checkout
    uses: actions/checkout@v4
    name: Build Java with Mvn
    uses: mvn package       